complaint/urls.py
from django.urls import path
from .views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('book/', book, name="book"),
    path('api_form/', api_form, name="api_form"),
    path('api_json/', api_json, name="api_json"),
] + static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("client.urls")),
    path('', include("server.urls")),
]  + static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

complaint/models.py
from django.db import models

# Create your models here.
class LibroRelamacion(models.Model):

    # del formato
    id                             = models.AutoField(primary_key=True, blank=False, null=False)

    # del reclamante
    reclamante_nombre              = models.CharField(max_length=50, blank=False, null=False)
    reclamante_domicilio           = models.CharField(max_length=50, blank=False, null=False)
    reclamante_tipo_documento      = models.CharField(max_length=9, blank=False, null=False, choices=[
        ("dni","DNI"),
        ("pasaporte","PASAPORTE"),
    ])
    reclamante_numero_documento    = models.CharField(max_length=12, blank=False, null=False) 
    reclamante_correo              = models.EmailField(max_length=50, blank=False, null=False) 
    reclamante_telefono_celular    = models.CharField(max_length=9, blank=False, null=False) 
    reclamante_menor_edad          = models.CharField(max_length=5, blank=False, null=False, choices=[
        ("menor","MENOR"),
        ("mayor","MAYOR"),
    ]) 

    # del apoderado
    apoderado_nombre              = models.CharField(max_length=50,blank=True,null=True) 
    apoderado_domicilio           = models.CharField(max_length=50,blank=True,null=True) 
    apoderado_correo              = models.EmailField(max_length=50,blank=True,null=True) 
    apoderado_telefono_celular    = models.CharField(max_length=9, blank=True, null=True)  
    
    # del bien contratado
    bien_tipo           = models.CharField(max_length=8, blank=False, null=False,choices=[
        ("producto","PRODUCTO"),
        ("servicio","SERVICIO"),
    ])
    bien_monto          = models.CharField(max_length=7, blank=False, null=False)   
    bien_descripcion    = models.TextField(max_length=255,blank=False, null=False) 
    
    # del reclamo
    reclamo_tipo        = models.CharField(max_length=7, blank=False, null=False, choices=[
        ("reclamo","RECLAMO"),
        ("queja","QUEJA"),
    ])
    reclamo_pedido      = models.TextField(max_length=100,blank=False, null=False)
    reclamo_descripcion = models.TextField(max_length=255,blank=False, null=False)
    reclamo_fecha       = models.DateField(blank=False, null=False)

    # del seguimiento
    reclamo_pdf         = models.FileField(upload_to="reclamos/", blank=True, null=True)
    solucion_pdf        = models.FileField(upload_to="soluciones/", blank=True, null=True)

    class Meta:
        db_table = "LibroRelamacion"

    def  __str__(self):
        return f'n°{self.id} ,  {self.reclamante_nombre},  {self.reclamo_fecha}'

complaint/views.py
import json
from datetime import date

from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods 
from django.views.decorators.csrf import csrf_exempt

from .oop import Formulario
from .models import LibroRelamacion

# Algorithms
def id_alogirhtm():

    query_id    = LibroRelamacion.objects.order_by("-id")
    new_id      = 1
    if query_id.exists() :
            new_id = query_id[0].id + 1

    return new_id

def post_algorithm(formulario):

    # data format
    if not formulario.apply_validations() :
        return JsonResponse(
            {"message"  :"Service Not Available", 
            "error"    : formulario.errors},
            safe=True,
            status=400)

    # no repetition
    previous = LibroRelamacion.objects.filter(
        reclamante_numero_documento = formulario.reclamante_numero_documento,
        reclamo_fecha = formulario.reclamo_fecha
    )
    if previous.exists():
        return JsonResponse(
            {"message"  :"Service Not Available", 
            "error"    : "The Document has been used in the last 24 hrs"},
            safe=True,
            status=400)

    # db insertion
    try :

        new_instance = LibroRelamacion(
            id                          = formulario.id,
            reclamante_nombre           = formulario.reclamante_nombre,
            reclamante_domicilio        = formulario.reclamante_domicilio,
            reclamante_tipo_documento   = formulario.reclamante_tipo_documento,
            reclamante_numero_documento = formulario.reclamante_numero_documento,
            reclamante_correo           = formulario.reclamante_correo,
            reclamante_telefono_celular = formulario.reclamante_telefono_celular,
            reclamante_menor_edad       = formulario.reclamante_menor_edad,
            apoderado_nombre            = formulario.apoderado_nombre,
            apoderado_domicilio         = formulario.apoderado_domicilio,
            apoderado_correo            = formulario.apoderado_correo,
            apoderado_telefono_celular  = formulario.apoderado_telefono_celular,
            bien_tipo                   = formulario.bien_tipo,
            bien_monto                  = formulario.bien_monto,
            bien_descripcion            = formulario.bien_descripcion,
            reclamo_tipo                = formulario.reclamo_tipo,
            reclamo_descripcion         = formulario.reclamo_descripcion,
            reclamo_pedido              = formulario.reclamo_pedido,
            reclamo_fecha               = formulario.reclamo_fecha,
            reclamo_pdf                 = formulario.reclamo_pdf,
        )
        new_instance.save()

    except:

        return JsonResponse(
            {"message"  :"Service Not Available", 
             "error"    : formulario.errors},
            safe=True,
            status=503)
        
    # pdf creation
    if not formulario.create_pdf() :
        return JsonResponse(
            {"message"  :"Service Not Available", 
             "error"    : formulario.errors},
            safe=True,
            status=503)
        
    # send email
    if not formulario.send_email() :
        return JsonResponse(
            {"message"  :"Service Not Available", 
             "error"    : formulario.errors},
            safe=True,
            status=503)

    # feedback 
    return JsonResponse(
        {"message"  :"success"},
        safe=True,
        status=200)  

# Views
@require_http_methods(["GET"])
def book(request):

    try:
        return render(request, 'book.html')
    
    except:
        return JsonResponse(
            {"message":"Service Not Available"},
            safe=True,
            status=500)

@require_http_methods(["POST"])
def api_form(request):

    # id value
    new_id      = id_alogirhtm()
    
    # query data
    formulario  = Formulario(
        id                          = new_id,
        reclamante_nombre           = request.POST.get("reclamante_nombre"),
        reclamante_domicilio        = request.POST.get("reclamante_domicilio"),
        reclamante_tipo_documento   = request.POST.get("reclamante_tipo_documento"),
        reclamante_numero_documento = request.POST.get("reclamante_numero_documento"),
        reclamante_correo           = request.POST.get("reclamante_correo"),
        reclamante_telefono_celular = request.POST.get("reclamante_telefono_celular"),
        reclamante_menor_edad       = request.POST.get("reclamante_menor_edad") or "mayor",
        apoderado_nombre            = request.POST.get("apoderado_nombre"),
        apoderado_domicilio         = request.POST.get("apoderado_domicilio"),
        apoderado_correo            = request.POST.get("apoderado_correo"),
        apoderado_telefono_celular  = request.POST.get("apoderado_telefono_celular"),
        bien_tipo                   = request.POST.get("bien_tipo"),
        bien_monto                  = request.POST.get("bien_monto"),
        bien_descripcion            = request.POST.get("bien_descripcion"),
        reclamo_tipo                = request.POST.get("reclamo_tipo"),
        reclamo_descripcion         = request.POST.get("reclamo_descripcion"),
        reclamo_pedido              = request.POST.get("reclamo_pedido"),
        reclamo_fecha               = str(date.today())
    )

    return post_algorithm(formulario)

@csrf_exempt
@require_http_methods(["POST"])
def api_json(request):

    # json formater
    query_dict  = json.loads(request.body)

    # security level
    hash = "NZo5JECQEl"
    if query_dict.get("hash") == hash:

        # id value
        new_id      = id_alogirhtm()

        # quey data
        formulario  = Formulario(
            id                          = new_id,
            reclamante_nombre           = query_dict.get("reclamante_nombre"),
            reclamante_domicilio        = query_dict.get("reclamante_domicilio"),
            reclamante_tipo_documento   = query_dict.get("reclamante_tipo_documento"),
            reclamante_numero_documento = query_dict.get("reclamante_numero_documento"),
            reclamante_correo           = query_dict.get("reclamante_correo"),
            reclamante_telefono_celular = query_dict.get("reclamante_telefono_celular"),
            reclamante_menor_edad       = query_dict.get("reclamante_menor_edad"),
            apoderado_nombre            = query_dict.get("apoderado_nombre"),
            apoderado_domicilio         = query_dict.get("apoderado_domicilio"),
            apoderado_correo            = query_dict.get("apoderado_correo"),
            apoderado_telefono_celular  = query_dict.get("apoderado_telefono_celular"),
            bien_tipo                   = query_dict.get("bien_tipo"),
            bien_monto                  = query_dict.get("bien_monto"),
            bien_descripcion            = query_dict.get("bien_descripcion"),
            reclamo_tipo                = query_dict.get("reclamo_tipo"),
            reclamo_descripcion         = query_dict.get("reclamo_descripcion"),
            reclamo_pedido              = query_dict.get("reclamo_pedido"),
            reclamo_fecha               = str(date.today())
        )
        
        return post_algorithm(formulario)
    
    return JsonResponse(
        {"message":"Service Not Available",
        "error":"not security layer achieved"},
        safe=True,
        status=400) 

complaint/templates/book.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sea Savor</title>
    <meta name="description" content="Discover a world of exquisite seafood dishes at SeaSavor. Our restaurant offers a variety of fresh catches prepared with passion and expertise. Join us for an unforgettable dining experience by the sea.">
    <meta name="keywords" content="seafood restaurant, ocean cuisine, fresh seafood, maritime dining, seafood dishes">
    <!--  CSS & LIBRARIES  -->
    <link rel="icon" type="image/x-icon" href="{% static 'complaint/assets/icon.png' %}">
    <link rel="stylesheet" href="{% static 'complaint/css/book.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
</head>
<body>
    <!-- HEADER -->
    <header id="header">
        <!-- NAVBAR CONTAINER -->
        <section class="nav_container">
            <!-- LATERAL MENU -->
            <div class="off_screen_menu">
                <ul>
                    <li><a target="_blank" href="https://squareup.com/us/es/appointments">Booking</a></li>
                    <li><a target="_blank" href="https://about.rappi.com/">Delivery</a></li>
                    <li><a target="_blank" href="{% static 'complaint/assets/promotions.pdf'%}">Promotions</a></li>
                    <li><hr></li>
                    <li><a href="{% url 'home'%}#aboutus">About Us</a></li>
                    <li><a href="{% url 'home'%}#schedule">Schedule</a></li>
                    <li><a href="{% url 'home'%}#menu">Menu</a></li>
                    <li><a href="{% url 'home'%}#locations">Location</a></li>
                    <li><a href="{% url 'home'%}#workwithus">Work With Us</a></li>
                </ul>
            </div>
            <!-- NAVBAR -->
            <nav class="nav">
                <!-- BUGER BUTTON -->
                <div class="nav_menu">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                <!-- LOGO -->
                <div class="nav_logo">
                    <img src="{% static 'complaint/assets/logo.png'%}" alt="SeaSavor restaurant logo: A stylized crab representing the freshness and quality of our seafood offerings.">
                </div>
                <!-- OPTIONS -->
                <div class="nav_buttons">
                    <a target="_blank" href="https://squareup.com/us/es/appointments">Booking</a>
                    <a target="_blank" href="https://about.rappi.com/">Delivery</a>
                    <a target="_blank" href="{% static 'complaint/assets/promotions.pdf'%}">Promotions</a>
                </div>
            </nav>
        </section>
        <!-- BANNER -->
        <section class="banner">
            <img src="{% static 'complaint/assets/logo.png'%}" alt="SeaSavor restaurant logo: A stylized crab representing the freshness and quality of our seafood offerings.">
            <h1>Sea Savor, From the Ocean to Your Plate</h1>
            <div>
                <a target="_blank" href="https://squareup.com/us/es/appointments">Booking</a>
                <a target="_blank" href="https://about.rappi.com/">Delivery</a>
                <a target="_blank" href="{% static 'complaint/assets/promotions.pdf'%}">Promotions</a>
            </div>
        </section>
    </header>

    <!-- FORM -->
    <main>
        <div class="form_container">
            <form action="{% url 'api_form'%}" method="POST">
                {% csrf_token %}

                <!-- RECLAMANTE -->
                <h2>Indetificación del Cosumidor Reclamante</h2>

                <!-- nombre -->
                <div class="input_box">
                    <label for="id_reclamante_nombre">Nombre Completo</label>
                    <input id="id_reclamante_nombre" type="text" required maxlength="50" name="reclamante_nombre">
                </div>
                <!-- domicilio -->
                <div class="input_box">
                    <label for="id_reclamante_domicilio">Domicilio</label>
                    <input id="id_reclamante_domicilio" type="text" required maxlength="50" name="reclamante_domicilio">
                </div>
                <!-- tipo documento -->
                <div class="input_select">
                    <label for="id_reclamante_tipo_documento">Tipo de Documento</label>
                    <select id="id_reclamante_tipo_documento" required name="reclamante_tipo_documento" >
                        <option value=>Selecciona un Documento</option>
                        <option value="dni">Dni</option>
                        <option value="pasaporte">Pasaporte</option>
                    </select>
                </div>
                <!-- numero documento -->
                <div class="input_box">
                    <label for="id_reclamante_numero_documento">Número de Documento</label>
                    <input id="id_reclamante_numero_documento" type="text" required minlength="8" maxlength="12", name="reclamante_numero_documento">
                </div>
                <!-- correo -->
                <div class="input_box">
                    <label for="id_reclamante_correo">Correo Electrónico</label>
                    <input id="id_reclamante_correo" type="email" required maxlength="50" name="reclamante_correo">
                </div>
                <!-- numero de contacto -->
                <div class="input_box">
                    <label for="id_reclamante_telefono_celular">Teléfono fijo / Celular</label>
                    <input id="id_reclamante_telefono_celular" type="text" required minlength="7" maxlength="9" name="reclamante_telefono_celular">
                </div>
                <!-- menor de edad -->
                <div class="input_check">
                    <input id="id_reclamante_menor_edad" type="checkbox" value="menor" name="reclamante_menor_edad" >
                    <label for="id_reclamante_menor_edad">Soy Menor de Edad</label>
                </div>
            
                <!-- APODERADO -->
                <div class="form_cotainer_parent">
                    <!-- nombre -->
                    <div class="input_box">
                        <label for="id_apoderado_nombre">Nombre Tutor / Padre / Madre </label>
                        <input id="id_apoderado_nombre" type="text" maxlength="50" name="apoderado_nombre">
                    </div>
                    <!-- domicilio -->
                    <div class="input_box">
                        <label for="id_apoderado_domiclio">Domicilio</label>
                        <input id="id_apoderado_domiclio" type="text" maxlength="50" name="apoderado_domicilio">
                    </div>
                    <!-- correo -->
                    <div class="input_box">
                        <label for="id_apoderado_correo">Correo Electrónico</label>
                        <input id="id_apoderado_correo" type="email" maxlength="50" name="apoderado_correo">
                    </div>
                    <!-- numero de contacto -->
                    <div class="input_box">
                        <label for="id_apoderado_telefono_celular">Teléfono fijo / Celular</label>
                        <input id="id_apoderado_telefono_celular" type="text" minlength="7" maxlength="9" name="apoderado_telefono_celular">
                    </div>
                </div>

                <hr/>

                <!-- BIEN -->
                <h2>Indetificación del Bien Reclamado</h2>
                
                <!-- tipo de bien -->
                <div class="input_radio">
                    <input id="id_bien_tipo_p" type="radio" required value="producto" name="bien_tipo">
                    <label for="id_bien_tipo_p">Producto</label>
                    <input id="id_bien_tipo_s" type="radio" required value="servicio" name="bien_tipo">
                    <label for="id_bien_tipo_s">Servicio</label>
                </div>
                <!-- monto reclamado -->
                <div class="input_box">
                    <label for="id_bien_monto">Monto Reclamado</label>
                    <input id="id_bien_monto" type="text" required maxlength="7" name="bien_monto">
                </div>
                <!-- descripcion -->
                <div class="input_area">
                    <label for="id_bien_descripcion">Descripción</label>
                    <textarea id="id_bien_descripcion" cols="30" required maxlength="255" name="bien_descripcion"></textarea>
                </div>

                <hr/>

                <!-- RECLAMO -->
                <h2>Detalle de Reclamación y Pedido del Consumidor</h2>
                
                <!-- tipo de reclamo -->
                <div class="input_radio">
                    <input id="id_reclamo_tipo_r" type="radio" required value="reclamo" name="reclamo_tipo">
                    <label for="id_reclamo_tipo_r">Reclamo</label>
                    <input id="id_reclamo_tipo_q" type="radio" required value="queja" name="reclamo_tipo">
                    <label for="id_reclamo_tipo_q">Queja</label>
                </div>
                <!-- descripcion reclamo -->
                <div class="input_area">
                    <label for="id_reclamo_descripcion">Detalle</label>
                    <textarea id="id_reclamo_descripcion" cols="30" required maxlength="255" name="reclamo_descripcion" ></textarea>
                </div>
                <!-- descripcion pedido -->
                <div class="input_area">
                    <label for="id_reclamo_pedido">Pedido</label>
                    <textarea id="id_reclamo_pedido" cols="30" required maxlength="255"  name="reclamo_pedido"></textarea>
                </div>

                <hr/>

                <!-- INFO -->
                <div class="input_info">
                    <p>* La formulación del reclamo no impide acudir a otras vías de solución de controversias ni es requisito previo para interponer una denuncia ante el INDECOPI.</p>
                    <p>* El proveedor deberá dar respuesta al reclamo en un plazo no mayor a quince (15) días calendario, pudiendo ampliar el plazo hasta por quince (15) días más, previa comunicación al consumidor.</p>
                </div>

                <!-- BOTON -->
                <div class="input_button">
                    <input type="submit" value="Enviar"/>
                </div>
            </form>
        </div>
    </main>

    <!-- FOOTER -->
    <footer>
        <!-- INFO -->
        <section class="info">
            <!-- LOGO -->
            <div class="info_logo"> 
                <img src="{% static 'complaint/assets/logo.png'%}" alt="SeaSavor restaurant logo: A stylized crab representing the freshness and quality of our seafood offerings.">
            </div>
            <!-- SECTIONS -->
            <div class="info_section">
                <h3>About Sea Savor</h3><br>
                <ul>
                    <li><a href="{% url 'home'%}#aboutus">About Us</a></li>
                    <li><a href="{% url 'home'%}#schedule">Schedule</a></li>
                    <li><a href="{% url 'home'%}#menu">Menu</a></li>
                    <li><a href="{% url 'home'%}#locations">Location</a></li>
                    <li><a href="{% url 'home'%}#workwithus">Work With Us</a></li>
                </ul>
            </div>
            <!-- MORE INFORMATION -->
            <div class="info_more">
                <h3>More Information</h3> 
                <ul>
                    <li><a class="book" target="_blank" href="{% url 'book' %}" alt="link for complaints book"></a></li>
                    <li><a class="reference" target="_blank" href="https://dontito.pe/" alt="link for reference website"></a></li>
                </ul>
            </div>
            <!-- MEDIA  -->
            <div class="info_media">
                <h3>Social Media Apps</h3>
                <ul>
                    <li><a class="insta" target="_blank" href="https://www.instagram.com/" alt="link fot instagram aacount"></a></li>
                    <li><a class="face" target="_blank" href="https://www.facebook.com/" alt="link for facebook account"></a></li>
                </ul>
            </div>
        </section>
        <!-- COPY RIGHT -->
        <div class="copyright">
            <span>© SeaSavor Restaurant, 2024. All Rights Reserved</span>
        </div>
    </footer>

    <!-- EXTRA -->
    <div id="extra">
        <!-- FIXED BUTTONS -->
        <div class="extra_button" >
            <a class="wp"  target="_blank" data-aos="zoom-in-up" href="https://wa.me/51981453194?text=I'm%20interested%20in%20your%20menu">
                <img src="{% static 'complaint/assets/whats_app.png'%}" alt="Chat on WhatsApp" />
            </a>
            <a class="top" data-aos="zoom-in-up" href="#header">
                <img src="{% static 'complaint/assets/up_arrow.png'%}" alt="Narrow to move back to the top" />
            </a>
        </div>
        <!-- FIXED OPTIONS -->
        <div class="extra_option" data-aos="zoom-in-up">
            <a href="#">Booking</a>
            <a href="#">Delivery</a>
            <a target="_blank" href="{% static 'complaint/assets/menu.pdf'%}">Menu</a>      
        </div>
    </div>

    <script src="{% static 'complaint/js/book.js' %}"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>
</html>